framework:
    messenger:
        transports:
            commands: '%env(MESSENGER_TRANSPORT_DSN)%/commands'
            events: '%env(MESSENGER_TRANSPORT_DSN)%/events'

        routing:
            App\Message\Signup: ['commands']
            App\Message\SignupCompleted: ['events']

        serializer: ~

        default_bus: app.messenger.command_bus

        buses:
            app.messenger.command_bus:
                middleware:
                    - messenger.middleware.validation

            app.messenger.event_bus:
                middleware:
                    - messenger.middleware.validation
