framework:
    messenger:
        transports:
            amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            App\Message\SignupCompleted: ['amqp']

        serializer: ~

        default_bus: app.messenger.command_bus

        buses:
            app.messenger.command_bus:
                middleware:
                    - messenger.middleware.validation

            app.messenger.event_bus:
                middleware:
                    - messenger.middleware.validation
